/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MapLibre */

#ifndef _Included_MapLibre
#define _Included_MapLibre
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MapLibre
 * Method:    render
 * Signature: (IIDDDD)[B
 */
JNIEXPORT jbyteArray JNICALL Java_MapLibre_render
  (JNIEnv *, jobject, jint, jint, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
