/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baremaps_maplibre_MapLibre */

#ifndef _Included_com_baremaps_maplibre_MapLibre
#define _Included_com_baremaps_maplibre_MapLibre
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baremaps_maplibre_MapLibre
 * Method:    render
 * Signature: (IIDDDD)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_baremaps_maplibre_MapLibre_render
        (JNIEnv *, jobject, jint, jint, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
