name: CI

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Install dependencies
      run: sudo apt-get install libcurl4-openssl-dev
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1.3
      with:
        submodule_update: ON
        package_generator: ON
    - uses: actions/upload-artifact@v2
      with:
        path: build/*.tar.gz
        name: artifact_${{ matrix.os }}_${{ matrix.configs }}.tar.gz
