name: CI

on: [push]

jobs:
  ubuntu-build:
    name: Build Project (Linux)
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt-get install curl libuv1 libuv1-dev libglfw3 libglfw3-dev zlib1g-dev automake libtool xutils-dev make cmake pkg-config python-pip libcurl4-openssl-dev libpng-dev libsqlite3-dev libllvm3.9 libxi-dev libglu1-mesa-dev x11proto-randr-dev x11proto-xext-dev libxrandr-dev x11proto-xf86vidmode-dev libxxf86vm-dev libxcursor-dev libxinerama-dev
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Checkout submodules
      run:  git submodule update --init --recursive
    - name: Configure project
      run: cmake .
    - name: Build project
      run: cmake --build .
  build-macos:
    name: Build Project (MacOS)
    runs-on: macos-latest
    steps:
      - name: Install dependencies
        run: brew install cmake ccache glfw ninja pkgconfig qt
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Checkout submodules
        run:  git submodule update --init --recursive
      - name: Configure project
        run: cmake .
      - name: Build project
        run: cmake --build .
  build-windows:
    name: Build Project (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Checkout submodules
        run:  git submodule update --init --recursive
      - name: Configure project
        run: cmake .
      - name: Build project
        run: cmake --build .

