name: CI

on:
  push:
    tags:
      - 'v*'
jobs:
  ubuntu-build:
    name: Build binaries (Linux)
    runs-on: ubuntu-18.04
    steps:
    - name: Update package repositories
      run: sudo apt-get update
    - name: Install packages
      run: sudo apt-get install -y build-essential libgl-dev cmake libcurl4-gnutls-dev libjpeg-dev libpng-dev zlib1g-dev pkg-config libglfw3-dev libuv1-dev llvm clang libicu-dev
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Checkout submodules
      run:  git submodule update --init --recursive
    - name: Configure project
      run: cmake -DCMAKE_BUILD_TYPE=Release .
    - name: Build project
      run: cmake --build . --config Release
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: libmaplibre-native.so
        path: native/libmaplibre-native.so
  macos-build:
    name: Build binaries (MacOS)
    runs-on: macos-latest
    steps:
      - name: Install dependencies
        run: brew install cmake ccache glfw ninja pkgconfig qt
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Checkout submodules
        run:  git submodule update --init --recursive
      - name: Configure project
        run: cmake -DCMAKE_BUILD_TYPE=Release .
      - name: Build project
        run: cmake --build . --config Release
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: libmaplibre-native.dylib
          path: native/libmaplibre-native.dylib
  release:
    name: Release binaries (Linux, MacOS)
    needs: [ubuntu-build, macos-build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: MapLibre Java ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Download libmaplibre-native.so
        uses: actions/download-artifact@v2
        with:
          name: libmaplibre-native.so
          path: ./native/
      - name: Download libmaplibre-native.dylib
        uses: actions/download-artifact@v2
        with:
          name: libmaplibre-native.dylib
          path: ./native/
      - name: Release libmaplibre-native.so
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./native/libmaplibre-native.so
          asset_name: libmaplibre-native.so
          asset_content_type: application/octet-stream
      - name: Release libmaplibre-native.dylib
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: native/libmaplibre-native.dylib
          asset_name: libmaplibre-native.dylib
          asset_content_type: application/octet-stream
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Create jar file
        run: mvn -B package --file pom.xml
      - name: Release maplibre-java.jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/maplibre-java.jar
          asset_name: maplibre-java.jar
          asset_content_type: application/octet-stream

