name: CI

on: [push]

jobs:
  ubuntu-build:
    name: Build binaries (Linux)
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt-get install curl libuv1 libuv1-dev libglfw3 libglfw3-dev zlib1g-dev automake libtool xutils-dev make cmake pkg-config python-pip libcurl4-openssl-dev libpng-dev libsqlite3-dev libllvm3.9 libxi-dev libglu1-mesa-dev x11proto-randr-dev x11proto-xext-dev libxrandr-dev x11proto-xf86vidmode-dev libxxf86vm-dev libxcursor-dev libxinerama-dev
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Checkout submodules
      run:  git submodule update --init --recursive
    - name: Configure project
      run: cmake .
    - name: Build project
      run: cmake --build .
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: libmaplibre-native.so
        path: native/libmaplibre-native.so
  macos-build:
    name: Build binaries (MacOS)
    runs-on: macos-latest
    steps:
      - name: Install dependencies
        run: brew install cmake ccache glfw ninja pkgconfig qt
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Checkout submodules
        run:  git submodule update --init --recursive
      - name: Configure project
        run: cmake .
      - name: Build project
        run: cmake --build .
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: libmaplibre-native.dylib
          path: native/libmaplibre-native.dylib
  release:
    name: Release binaries (Linux, MacOS)
    needs: [ubuntu-build, macos-build]
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Baremaps ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Download libmaplibre-native.so
        uses: actions/download-artifact@v2
        with:
          name: libmaplibre-native.so
          path: ./native/
      - name: Download libmaplibre-native.dylib
        uses: actions/download-artifact@v2
        with:
          name: libmaplibre-native.dylib
          path: ./native/
      - name: Release libmaplibre-native.so
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./native/libmaplibre-native.so
          asset_name: libmaplibre-native.so
          asset_content_type: application/octet-stream
      - name: Release libmaplibre-native.dylib
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: native/libmaplibre-native.dylib
          asset_name: libmaplibre-native.dylib
          asset_content_type: application/octet-stream

